name: Check tox tests, lint and types

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check_document:
    name: Check packaging 📦
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 20
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install tools
      run: |
        pip install -U pip
        pip install tox tox-gh-actions coveralls coverage[toml]
    - name: Check invocation with Python2
      run: |
        ! python2 -m aqt help
        [[ $(python2 -m aqt help) == "aqtinstall requires python 3!" ]]
    - name: Check
      run: tox
      env:
        PYTEST_ADDOPTS: --cov-config=pyproject.toml --cov --cov-append --verbose
    - name: Upload Coverage
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
